import pandas as pd

# Provided data
data = [
    {"No.": 59, "Drug Name": "Ultomiris", "Active Ingredient": "ravulizumab", "Approval Date": "12/21/2018", "FDA-approved use on approval date*": "To treat paroxysmal nocturnal hemoglobinuria (PNH)"},
    {"No.": 58, "Drug Name": "Elzonris", "Active Ingredient": "tagraxofusp-erzs", "Approval Date": "12/21/2018", "FDA-approved use on approval date*": "To treat blastic plasmacytoid dendritic cell neoplasm (BPDCN)"},
    {"No.": 57, "Drug Name": "Asparlas", "Active Ingredient": "calaspargase pegol-mknl", "Approval Date": "12/20/2018", "FDA-approved use on approval date*": "To treat acute lymphoblastic leukemia (ALL) in pediatric and young adult patients age 1 month to 21 years"},
    {"No.": 56, "Drug Name": "Motegrity", "Active Ingredient": "prucalopride", "Approval Date": "12/14/2018", "FDA-approved use on approval date*": "To treat chronic idiopathic constipation"},
    {"No.": 55, "Drug Name": "Xospata", "Active Ingredient": "gilteritinib", "Approval Date": "11/28/2018", "FDA-approved use on approval date*": "To treat patients who have relapsed or refractory acute myeloid leukemia (AML)"},
    {"No.": 54, "Drug Name": "Firdapse", "Active Ingredient": "amifampridine", "Approval Date": "11/28/2028", "FDA-approved use on approval date*": "To treat Lambert-Eaton myasthenic syndrome (LEMS) in adults"},
    {"No.": 53, "Drug Name": "Vitrakvi", "Active Ingredient": "larotrectinib", "Approval Date": "11/26/2018", "FDA-approved use on approval date*": "To treat patients whose cancers have a specific genetic feature (biomarker)"},
    {"No.": 52, "Drug Name": "Daurismo", "Active Ingredient": "glasdegib", "Approval Date": "11/21/2018", "FDA-approved use on approval date*": "To treat newly-diagnosed acute myeloid leukemia (AML) in adult patients"},
    {"No.": 51, "Drug Name": "Gamifant", "Active Ingredient": "emapalumab-lzsgemapalumab-lzsg", "Approval Date": "11/20/2018", "FDA-approved use on approval date*": "To treat primary hemophagocytic lymphohistiocytosis (HLH)"},
    {"No.": 50, "Drug Name": "Aemcolo", "Active Ingredient": "rifamycin", "Approval Date": "11/16/2018", "FDA-approved use on approval date*": "To treat travelers’ diarrhea"},
    {"No.": 49, "Drug Name": "Yupelri", "Active Ingredient": "revefenacin", "Approval Date": "11/9/2018", "FDA-approved use on approval date*": "To treat patients with chronic obstructive pulmonary disease (COPD)"},
    {"No.": 48, "Drug Name": "Lorbrena", "Active Ingredient": "lorlatinib", "Approval Date": "11/2/2018", "FDA-approved use on approval date*": "To treat patients with anaplastic lymphoma kinase (ALK)-positive metastatic non-small cell lung cancer"},
    {"No.": 47, "Drug Name": "Xofluza", "Active Ingredient": "baloxavir marboxil", "Approval Date": "10/24/2018", "FDA-approved use on approval date*": "To treat acute uncomplicated influenza in patients who have been symptomatic for no more than 48 hours."},
    {"No.": 46, "Drug Name": "Talzenna", "Active Ingredient": "talazoparib", "Approval Date": "10/16/2018", "FDA-approved use on approval date*": "To treat locally advanced or metastatic breast cancer patients with a germline BRCA mutation."},
    {"No.": 45, "Drug Name": "Tegsedi", "Active Ingredient": "inotersen", "Approval Date": "10/5/2018", "FDA-approved use on approval date*": "To treat polyneuropathy of hereditary transthyretin-mediated amyloidosis in adults"},
    {"No.": 44, "Drug Name": "Revcovi", "Active Ingredient": "elapegademase-lvlr", "Approval Date": "10/5/2018", "FDA-approved use on approval date*": "To treat Adenosine Deaminase-Severe Combined Immunodeficiency (ADA-SCID)"},
    {"No.": 43, "Drug Name": "Nuzyra", "Active Ingredient": "omadacycline", "Approval Date": "10/2/2018", "FDA-approved use on approval date*": "To treat community-acquired bacterial pneumonia and acute bacterial skin and skin structure infections"},
    {"No.": 42, "Drug Name": "Seysara", "Active Ingredient": "sarecycline", "Approval Date": "10/1/2018", "FDA-approved use on approval date*": "To treat inflammatory lesions of non-nodular moderate to severe acne vulgaris in patients 9 years of age and older"},
    {"No.": 41, "Drug Name": "Libtayo", "Active Ingredient": "cemiplimab-rwlc", "Approval Date": "9/28/2018", "FDA-approved use on approval date*": "To treat cutaneous squamous cell carcinoma (CSCC)"},
    {"No.": 40, "Drug Name": "Vizimpro", "Active Ingredient": "dacomitinib", "Approval Date": "9/27/2018", "FDA-approved use on approval date*": "To treat metastatic non-small-cell lung cancer"},
    {"No.": 39, "Drug Name": "Emgality", "Active Ingredient": "galcanezumab-gnlm", "Approval Date": "9/27/2018", "FDA-approved use on approval date*": "For the preventive treatment of migraine in adults"},
    {"No.": 38, "Drug Name": "Copiktra", "Active Ingredient": "duvelisib", "Approval Date": "9/24/2018", "FDA-approved use on approval date*": "To treat relapsed or refractory chronic lymphocytic leukemia, small lymphocytic lymphoma and follicular lymphoma"},
    {"No.": 37, "Drug Name": "Ajovy", "Active Ingredient": "fremanezumab-vfrm", "Approval Date": "9/14/2018", "FDA-approved use on approval date*": "For the preventive treatment of migraine in adults"},
    {"No.": 36, "Drug Name": "Lumoxiti", "Active Ingredient": "moxetumomab pasudotox-tdfk", "Approval Date": "9/13/2018", "FDA-approved use on approval date*": "To treat hairy cell leukemia"},
    {"No.": 35, "Drug Name": "Pifeltro", "Active Ingredient": "doravirine", "Approval Date": "8/30/2018", "FDA-approved use on approval date*": "To treat HIV-1 infection in adult patients"},
    {"No.": 34, "Drug Name": "Xerava", "Active Ingredient": "eravacycline", "Approval Date": "8/27/2018", "FDA-approved use on approval date*": "To treat complicated intra-abdominal infections in patients 18 years of age and older"},
    {"No.": 33, "Drug Name": "Takhzyro", "Active Ingredient": "lanadelumab", "Approval Date": "8/23/2018", "FDA-approved use on approval date*": "To treat types I and II hereditary angioedema"},
    {"No.": 32, "Drug Name": "Oxervate", "Active Ingredient": "cenegermin-bkbj", "Approval Date": "8/22/2018", "FDA-approved use on approval date*": "To treat neurotrophic keratitis"},
    {"No.": 31, "Drug Name": "Diacomit", "Active Ingredient": "stiripentol", "Approval Date": "8/20/2018", "FDA-approved use on approval date*": "To treat seizures associated with Dravet syndrome in patients 2 years of age and older taking clobazam"},
    {"No.": 30, "Drug Name": "Galafold", "Active Ingredient": "migalastat", "Approval Date": "8/10/2018", "FDA-approved use on approval date*": "To treat adults with Fabry disease."},
    {"No.": 29, "Drug Name": "Annovera", "Active Ingredient": "segesterone acetate and ethinyl estradiol vaginal system", "Approval Date": "8/10/2018", "FDA-approved use on approval date*": "New vaginal ring used to prevent pregnancy for an entire year"},
    {"No.": 28, "Drug Name": "Onpattro", "Active Ingredient": "patisiran", "Approval Date": "8/10/2018", "FDA-approved use on approval date*": "To treat the polyneuropathy of hereditary transthyretin-mediated amyloidosis in adult patients"},
    {"No.": 27, "Drug Name": "Poteligeo", "Active Ingredient": "mogamulizumab-kpkc", "Approval Date": "8/8/2018", "FDA-approved use on approval date*": "To treat two rare types of non-Hodgkin lymphoma"},
    {"No.": 26, "Drug Name": "Mulpleta", "Active Ingredient": "lusutrombopag", "Approval Date": "7/31/2018", "FDA-approved use on approval date*": "To treat thrombocytopenia in adult patients with chronic liver disease who are scheduled to undergo a procedure"},
    {"No.": 25, "Drug Name": "Omegaven", "Active Ingredient": "fish oil triglycerides", "Approval Date": "7/27/2018", "FDA-approved use on approval date*": "As a source of calories and fatty acids in pediatric patients with parenteral nutrition-associated cholestasis"},
    {"No.": 24, "Drug Name": "Orilissa", "Active Ingredient": "elagolix sodium", "Approval Date": "7/23/2018", "FDA-approved use on approval date*": "For the management of moderate to severe pain associated with endometriosis"},
    {"No.": 23, "Drug Name": "Krintafel", "Active Ingredient": "tafenoquine", "Approval Date": "7/20/2018", "FDA-approved use on approval date*": "For the radical cure (prevention of relapse) of Plasmodium vivax malaria"},
    {"No.": 22, "Drug Name": "Tibsovo", "Active Ingredient": "ivosidenib", "Approval Date": "7/20/2018", "FDA-approved use on approval date*": "To treat patients with relapsed or refractory acute myeloid leukemia"},
    {"No.": 21, "Drug Name": "TPOXX", "Active Ingredient": "tecovirimat", "Approval Date": "7/13/2018", "FDA-approved use on approval date*": "To treat smallpox"},
    {"No.": 20, "Drug Name": "Braftovi", "Active Ingredient": "encorafenib", "Approval Date": "6/27/2018", "FDA-approved use on approval date*": "To treat unresectable or metastatic melanoma"},
    {"No.": 19, "Drug Name": "Mektovi", "Active Ingredient": "binimetinib", "Approval Date": "6/27/2018", "FDA-approved use on approval date*": "To treat unresectable or metastatic melanoma"},
    {"No.": 18, "Drug Name": "Zemdri", "Active Ingredient": "plazomicin", "Approval Date": "6/25/2018", "FDA-approved use on approval date*": "To treat adults with complicated urinary tract infections"},
    {"No.": 17, "Drug Name": "Epidioloex", "Active Ingredient": "cannabidiol", "Approval Date": "6/25/2018", "FDA-approved use on approval date*": "To treat rare, severe forms of epilepsy"},
    {"No.": 16, "Drug Name": "Moxidectin", "Active Ingredient": "moxidectin", "Approval Date": "6/13/2018", "FDA-approved use on approval date*": "To treat onchocerciasis due to Onchocerca volvulus in patients aged 12 years and older"},
    {"No.": 15, "Drug Name": "Olumiant", "Active Ingredient": "baricitinib", "Approval Date": "5/31/2018", "FDA-approved use on approval date*": "To treat moderately to severely active rheumatoid arthritis"},
    {"No.": 14, "Drug Name": "Palynziq", "Active Ingredient": "pegvaliase-pqpz", "Approval Date": "5/24/2018", "FDA-approved use on approval date*": "To treat adults with a rare and serious genetic disease known as phenylketonuria (PKU)"},
    {"No.": 13, "Drug Name": "Doptelet", "Active Ingredient": "avatrombopag", "Approval Date": "5/21/2018", "FDA-approved use on approval date*": "To treat low blood platelet count (thrombocytopenia) in adults with chronic liver disease who are scheduled to undergo a medical or dental procedure"},
    {"No.": 12, "Drug Name": "Lokelma", "Active Ingredient": "sodium zirconium cyclosilicate", "Approval Date": "5/18/2018", "FDA-approved use on approval date*": "To treat hyperkalemia"},
    {"No.": 11, "Drug Name": "Aimovig", "Active Ingredient": "erenumab-aooe", "Approval Date": "5/17/2018", "FDA-approved use on approval date*": "For the preventive treatment for migraine"},
    {"No.": 10, "Drug Name": "Lucemyra", "Active Ingredient": "lofexidine hydrochloride", "Approval Date": "5/16/2018", "FDA-approved use on approval date*": "For the non-opioid treatment for management of opioid withdrawal symptoms in adults"},
    {"No.": 9, "Drug Name": "Akynzeo", "Active Ingredient": "fosnetupitant and palonosetron", "Approval Date": "4/19/2018", "FDA-approved use on approval date*": "To prevent acute and delayed nausea and vomiting associated with initial and repeat courses of highly emetogenic cancer chemotherapy"},
    {"No.": 8, "Drug Name": "Crysvita", "Active Ingredient": "burosumab-twza", "Approval Date": "4/17/2018", "FDA-approved use on approval date*": "To treat adults and children ages 1 year and older with x-linked hypophosphatemia (XLH), a rare, inherited form of rickets"},
    {"No.": 7, "Drug Name": "Tavalisse", "Active Ingredient": "fostamatinib", "Approval Date": "4/17/2018", "FDA-approved use on approval date*": "To treat thrombocytopenia in adult patients with persistent or chronic immune thrombocytopenia (ITP)"},
    {"No.": 6, "Drug Name": "Ilumya", "Active Ingredient": "tildrakizumab", "Approval Date": "3/20/2018", "FDA-approved use on approval date*": "To treat adults with moderate-to-severe plaque psoriasis who are candidates for systemic therapy or phototherapy"},
    {"No.": 5, "Drug Name": "Trogarzo", "Active Ingredient": "ibalizumab-uiyk", "Approval Date": "3/6/2018", "FDA-approved use on approval date*": "To treat HIV patients who have limited treatment options"},
    {"No.": 4, "Drug Name": "Erleada", "Active Ingredient": "apalutamide", "Approval Date": "2/14/2018", "FDA-approved use on approval date*": "To treat a certain type of prostate cancer using novel clinical trial endpoint"},
    {"No.": 3, "Drug Name": "Symdeko", "Active Ingredient": "tezacaftor; ivacaftor", "Approval Date": "2/12/2018", "FDA-approved use on approval date*": "To treat cystic fibrosis in patients age 12 years and older"},
    {"No.": 2, "Drug Name": "Biktarvy", "Active Ingredient": "bictegravir, embitcitabine, tenofovir alafenamide", "Approval Date": "2/7/2018", "FDA-approved use on approval date*": "To treat infection in adults who have no antiretroviral treatment history or to replace the current antiretroviral regimen"},
    {"No.": 1, "Drug Name": "Lutathera", "Active Ingredient": "lutetium Lu 177 dotatate", "Approval Date": "1/26/2018", "FDA-approved use on approval date*": "To treat a type of cancer that affects the pancreas or gastrointestinal tract called gastroenteropancreatic neuroendocrine tumors (GEP-NETs)."}
]

# Create a DataFrame
df = pd.DataFrame(data)

# Save to Excel
df.to_excel('Noval Drugs Approvals for 2018.xlsx', index=False)
